STEP SIXTH: 1. pageable added 2. swagger added 3. code style improved
MateuszSeler/book_store_app pull request #5
Opened 2024-12-18 19:39 UTC by MateuszSeler

2024-12-19 08:52 UTC, slade13 approved these changes
Good job on implementing those 3 features, next time please split each feature into separate pull requests. For each task on Mate platform please provide the link to the PR not to the branch.

2024-12-19 08:52 UTC, slade13 commented on src/main/java/app/exception/CustomGlobalExceptionHandler.java
> -
Unnecessary blank line removed. While this is not a critical issue, maintaining consistent formatting can improve code readability.

2024-12-19 08:52 UTC, slade13 commented on src/main/java/app/exception/CustomGlobalExceptionHandler.java
> -
Unnecessary blank lines removed. Consistent use of blank lines can help improve code readability by separating logical sections of code.

2024-12-21 13:13 UTC, George-Khomiak requested changes
Minor comments

2024-12-21 13:13 UTC, George-Khomiak commented on src/main/java/app/model/User.java
> +@SQLDelete(sql = "UPDATE books SET is_Deleted = true WHERE id = ?")
Update **users** not books

2024-12-21 13:13 UTC, George-Khomiak commented on src/main/java/app/repository/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Nice

2024-12-21 13:13 UTC, George-Khomiak commented on src/main/java/app/security/AuthenticationService.java
> +
empty line

2024-12-21 13:13 UTC, George-Khomiak commented on src/main/java/app/mapper/UserMapper.java
> +
empty line

2024-12-21 13:13 UTC, George-Khomiak commented on src/main/java/app/service/UserServiceImpl.java
> +        User user = new User();
Can we use simply userMapper here?

2024-12-21 15:36 UTC, MateuszSeler commented on src/main/java/app/model/User.java
> +@SQLDelete(sql = "UPDATE books SET is_Deleted = true WHERE id = ?")
Stupid mistake... Thx!

2024-12-21 16:23 UTC, MateuszSeler commented on src/main/java/app/service/UserServiceImpl.java
> +        User user = new User();
I simplified the code I as you asked for. I was following the instructions. Apparently, such solution will be used in next lessons.

2024-12-21 20:54 UTC, George-Khomiak approved these changes

2024-12-21 21:03 UTC, merged